### ISSUE TITLE
This tool crashes Spotify

### ISSUE THREAD

**Issue by z3nth10n** [meik1710/Spotify1710#5]
There are the dumps

[reports.zip](https://github.com/meik1710/Spotify1710/files/3347951/reports.zip)

**Comment by meik1710** [comment]
It depends on a few things. What version are you using ? Are you starting Spotify1710 before you start Spotify ? Sometimes Spotify crashes while listening to a song. Thats probably due to the way i am hooking the "new track procedure".

**Comment by z3nth10n** [comment]
I was using the version "1.1.9.383"... I think this is caused due to wrong pointers? Idk, because I even don't know how to get them.

Could you make a document explaining the process about how did you get those pointers? (I would really appreciate it) I was researching about this, I suppose that debugging the app is a good techique, but I'm not able to find a good tool for such task.

**Comment by meik1710** [comment]
The files are shown in blue because they are compressed. There is no way to hide the console in the current release, but you can always make your own build without a console. Im currently not thinking about making a documentation for finding the right offsets, but i could still write you on telegram when i have time

**Comment by z3nth10n** [comment]
Ok, just talk to me by Telegram... I need to compare some offsets but I don't have the Standalones from older versions of Spotify. (Because I need to check if it's the right method to obtain them... By the moment, I will be copying your addresses until I learn about how to get them...)
